id: 9242876a-41c4-42f8-96f8-ac92d6025406
title: Settings
blueprint: global_settings
data:
  site_name: 'Personal Journal of Jack McDade'
  links:
    -
      name: Home
      url: '/'
    -
      name: JackMcDade.com
      url: 'https://jackmcdade.com'
    -
      name: Twitter
      url: 'https://twitter.com/jackmcdade'
    -
      name: E-Mail Me
      url: 'mailto:shout@jackmcdade.com'
